spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: huiji
    password: 1234
    driver-class-name: org.postgresql.Driver


logging:
  file:
    name: C:\Project1\demo (2)\log\logback.log  # 로깅 파일 위치이다.
    max-history: 7 # 로그 파일 삭제 주기이다. 7일 이후 로그는 삭제한다.
    max-size: 500MB  # 로그 파일 하나당 최대 파일 사이즈이다.
  level:  # 각 package 별로 로깅 레벨을 지정할 수 있다.
    kr\ac\gwnu : warn
#    C:\Project1\demo728\demo (2) (2)\log\spring.log : debug

       #file(warn)
      #녹색 - trace, debug, info
      #노란색 - warn
      #빨간색 - error, fatal


